import 'package:by_cycle/models/custom_date_time_range.dart';
import 'package:by_cycle/models/daily_data_input.dart';
import 'package:by_cycle/models/user.dart';

List<DateTime> initialSpottingOccurrences = [
  DateTime(2024, 6, 10), // Example: Specific date
];

User user_after_onboardCalendar = User(
  name: 'PA Lucia',
  email: 'pa_lucia@example.com',
  lastPeriod: DateTime(2024, 5, 24),
  menstruationPhaseLength: 4,
  completeCycleLength: 28,
  timeToFallAsleep: 20,
  cycleRegular: true,
  cycleHeavy: false,
  would_like_reminders_about_data_log_in: false,
  would_like_reminders_about_self_care_checklist: false,
  dailyDataInput: [
    DailyDataInput(date: DateTime(2024, 5, 24), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 5, 25), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 5, 26), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 5, 27), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 5, 28), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 5, 29), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 5, 30), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 5, 31), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 6, 1), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 6, 2), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 6, 3), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 6, 4), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 6, 5), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 6, 6), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 6, 7), phase: "ovulation"),
    DailyDataInput(date: DateTime(2024, 6, 8), phase: "ovulation"),
    DailyDataInput(date: DateTime(2024, 6, 9), phase: "ovulation"),
    DailyDataInput(date: DateTime(2024, 6, 10), phase: "ovulation"),
    DailyDataInput(date: DateTime(2024, 6, 11), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 6, 12), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 6, 13), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 6, 14), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 6, 15), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 6, 16), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 6, 17), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 6, 18), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 6, 19), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 6, 20), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 6, 21), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 6, 22), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 6, 23), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 6, 24), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 6, 25), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 6, 26), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 6, 27), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 6, 28), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 6, 29), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 6, 30), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 7, 1), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 7, 2), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 7, 3), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 7, 4), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 7, 5), phase: "ovulation"),
    DailyDataInput(date: DateTime(2024, 7, 6), phase: "ovulation"),
    DailyDataInput(date: DateTime(2024, 7, 7), phase: "ovulation"),
    DailyDataInput(date: DateTime(2024, 7, 8), phase: "ovulation"),
    DailyDataInput(date: DateTime(2024, 7, 9), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 7, 10), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 7, 11), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 7, 12), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 7, 13), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 7, 14), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 7, 15), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 7, 16), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 7, 17), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 7, 18), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 7, 19), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 7, 20), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 7, 21), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 7, 22), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 7, 23), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 7, 24), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 7, 25), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 7, 26), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 7, 27), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 7, 28), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 7, 29), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 7, 30), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 7, 31), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 8, 1), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 8, 2), phase: "ovulation"),
    DailyDataInput(date: DateTime(2024, 8, 3), phase: "ovulation"),
    DailyDataInput(date: DateTime(2024, 8, 4), phase: "ovulation"),
    DailyDataInput(date: DateTime(2024, 8, 5), phase: "ovulation"),
    DailyDataInput(date: DateTime(2024, 8, 6), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 8, 7), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 8, 8), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 8, 9), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 8, 10), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 8, 11), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 8, 12), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 8, 13), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 8, 14), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 8, 15), phase: "luteal"),
    DailyDataInput(date: DateTime(2024, 8, 16), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 8, 17), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 8, 18), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 8, 19), phase: "menstruation"),
    DailyDataInput(date: DateTime(2024, 8, 20), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 8, 21), phase: "follicular"),
    DailyDataInput(date: DateTime(2024, 8, 22), phase: "follicular")
  ],

  algorithmData: {}, // Using default values for algorithmData
  phaseRanges: [
    CustomDateTimeRange(
        start: DateTime(2024, 5, 24),
        end: DateTime(2024, 5, 27),
        phase: "menstrual"),
    CustomDateTimeRange(
        start: DateTime(2024, 5, 28),
        end: DateTime(2024, 6, 6),
        phase: "follicular"),
    CustomDateTimeRange(
        start: DateTime(2024, 6, 7),
        end: DateTime(2024, 6, 10),
        phase: "ovulation"),
    CustomDateTimeRange(
        start: DateTime(2024, 6, 11),
        end: DateTime(2024, 6, 20),
        phase: "luteal"),
    CustomDateTimeRange(
        start: DateTime(2024, 6, 21),
        end: DateTime(2024, 6, 24),
        phase: "menstrual"),
    CustomDateTimeRange(
        start: DateTime(2024, 6, 25),
        end: DateTime(2024, 7, 4),
        phase: "follicular"),
    CustomDateTimeRange(
        start: DateTime(2024, 7, 5),
        end: DateTime(2024, 7, 8),
        phase: "ovulation"),
    CustomDateTimeRange(
        start: DateTime(2024, 7, 9),
        end: DateTime(2024, 7, 18),
        phase: "luteal"),
    CustomDateTimeRange(
        start: DateTime(2024, 7, 19),
        end: DateTime(2024, 7, 22),
        phase: "menstrual"),
    CustomDateTimeRange(
        start: DateTime(2024, 7, 23),
        end: DateTime(2024, 8, 1),
        phase: "follicular"),
    CustomDateTimeRange(
        start: DateTime(2024, 8, 2),
        end: DateTime(2024, 8, 5),
        phase: "ovulation"),
    CustomDateTimeRange(
        start: DateTime(2024, 8, 6),
        end: DateTime(2024, 8, 15),
        phase: "luteal"),
    CustomDateTimeRange(
        start: DateTime(2024, 8, 16),
        end: DateTime(2024, 8, 19),
        phase: "menstrual"),
    CustomDateTimeRange(
        start: DateTime(2024, 8, 20),
        end: DateTime(2024, 8, 22),
        phase: "follicular"),
  ],
);
