// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWbgOWPs9ca6AtKF_dLrWiw6acJKBvj2c',
    appId: '1:303584259226:web:7e32fda6dabd653ef08323',
    messagingSenderId: '303584259226',
    projectId: 'bycycle-7da95',
    authDomain: 'bycycle-7da95.firebaseapp.com',
    storageBucket: 'bycycle-7da95.appspot.com',
    measurementId: 'G-7DHXG0C25Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA0SgkJT2zvzMgazAA2h1P4QDqll4Nyik',
    appId: '1:303584259226:android:c6076d29d96b929cf08323',
    messagingSenderId: '303584259226',
    projectId: 'bycycle-7da95',
    storageBucket: 'bycycle-7da95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK0aFyXWMmK0LJptlxQX6t7UfcgaBSQso',
    appId: '1:303584259226:ios:91f5265d5faca8c0f08323',
    messagingSenderId: '303584259226',
    projectId: 'bycycle-7da95',
    storageBucket: 'bycycle-7da95.appspot.com',
    iosBundleId: 'com.ignite.bycycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK0aFyXWMmK0LJptlxQX6t7UfcgaBSQso',
    appId: '1:303584259226:ios:91f5265d5faca8c0f08323',
    messagingSenderId: '303584259226',
    projectId: 'bycycle-7da95',
    storageBucket: 'bycycle-7da95.appspot.com',
    iosBundleId: 'com.ignite.bycycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWbgOWPs9ca6AtKF_dLrWiw6acJKBvj2c',
    appId: '1:303584259226:web:5095da268cb25551f08323',
    messagingSenderId: '303584259226',
    projectId: 'bycycle-7da95',
    authDomain: 'bycycle-7da95.firebaseapp.com',
    storageBucket: 'bycycle-7da95.appspot.com',
    measurementId: 'G-HK44V77TWR',
  );
}
