// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN3jSdYqs4Y_iqo4JkVbld0rdZO1Xh0z8',
    appId: '1:198712519729:web:3d2dcb6b2b394e2eeeb910',
    messagingSenderId: '198712519729',
    projectId: 'bycycle-1e6ed',
    authDomain: 'bycycle-1e6ed.firebaseapp.com',
    storageBucket: 'bycycle-1e6ed.appspot.com',
    measurementId: 'G-Y2T00MQKEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCooK1ZiVQY_LoEwHbAc2gFAEYj3aavZsg',
    appId: '1:198712519729:android:254cba76f3e5d2dbeeb910',
    messagingSenderId: '198712519729',
    projectId: 'bycycle-1e6ed',
    storageBucket: 'bycycle-1e6ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjX05m1CfwWEPII4wRSqmcjOaOoyilxlI',
    appId: '1:198712519729:ios:1a78c626f80c43aeeeb910',
    messagingSenderId: '198712519729',
    projectId: 'bycycle-1e6ed',
    storageBucket: 'bycycle-1e6ed.appspot.com',
    iosBundleId: 'com.example.byCycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjX05m1CfwWEPII4wRSqmcjOaOoyilxlI',
    appId: '1:198712519729:ios:1a78c626f80c43aeeeb910',
    messagingSenderId: '198712519729',
    projectId: 'bycycle-1e6ed',
    storageBucket: 'bycycle-1e6ed.appspot.com',
    iosBundleId: 'com.example.byCycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN3jSdYqs4Y_iqo4JkVbld0rdZO1Xh0z8',
    appId: '1:198712519729:web:17ed0c36f3434c9beeb910',
    messagingSenderId: '198712519729',
    projectId: 'bycycle-1e6ed',
    authDomain: 'bycycle-1e6ed.firebaseapp.com',
    storageBucket: 'bycycle-1e6ed.appspot.com',
    measurementId: 'G-V647PMMR8N',
  );

}